# Conclusions

This second iteration of the Brazil-Europe operational ANS performance comparison report builds on the joint project between the DECEA Performance Section and the Performance Review Unit of EUROCONTROL.

The collaboration project aims at the development of a joint and common understanding of agreed metrics and definitions to compare, understand, and improve operational air navigation system performance. 
This report uses a subset of the key performance indicators established by ICAO’s GANP. 
The work is also used as a show-case for applying the GANP indicators within a bi-regional project, to augment the associated guidance material, and inform further multi-regional comparison efforts. 
The comparison shows similarities and differences in the observed performance in both regions. 
Throughout the report several observations and ideas for future research have been identified. 
This will allow to further develop and complement the performance framework.

The first part of this report examined commonalities and differences in terms of air traffic management organisation and performance influencing factors, such as air traffic demand and fleet composition. 
These factors can have a large influence on the observed performance. 
Overall, air navigation service provision is more fragmented in Europe with local/national ANSPs and their respective control units. 
The integrated civil/military service provision is inherent to the organisation of DECEA and the Brazilian system. 
Irrespective of the airspace volume, the large difference in numbers of control units in Europe and Brazil demonstrates this. 
Both systems operate a central flow management center to ensure network wide flow management processes and functions.

Both regions encountered an unprecedented decline of air traffic in response to COVID-19. Regional and global traffic restrictions resulted however in different patterns regarding the initial and continued recovery. European traffic levels showed several waves in light of the variety of national and pan-European measures. The Brazilian evolution of traffic showed a delayed wave pattern in comparison with Europe, however, showed a more steady recovery overall.   
Additional diversity in terms of air traffic was observed across the Brazilian airports as there was a significant share of light types serviced. Within the European context, the share of light types was mostly negligible. 
A higher share of wide-body (heavy) aircraft operated from the European airports including a higher level of international connectivity. 
This is more nuanced in Brazil where the level of international connections is more centralised.

In terms of predictability and puncutality, the results were strongly influenced by the prevailing COVID-19 traffic evolution.
Both systems suffered from the disruption of schedules and cancellations of flight connections.
Europe showed a higher number of aircraft arriving more than 15 minutes ahead of schedule (early arrivals) and flights departing later than 15 minutes after their scheduled time). In Brazil, this behaviour was only observed for arriving traffic.
Returning traffic levels drove a gradual move towards punctuality levels comparable to 2019 levels. However, there is a higher level of uncertainty in terms of movements in both regions.

Runway system capacities in Brazil were adapted over the past years to accommodate the projected growth. 
Respective capacities at European airports were constant over the horizon of this report as part of the local/national declaration process and operated traffic levels. 
Despite the COVID-related change in traffic, accomplished peak throughput levels ranged at the level of earlier years.
This suggests that airport runway system capacities are commensurate with the observed (and expected) traffic levels and represent not a primary driver for operational inefficiencies during the arrival phase.

Operational efficiency in this report is measured for the taxi-in and taxi-out phase, and additional time in terminal airspace.
Similar patterns were observed at the different airports in both regions. 
On average, arriving traffic was observing little additional taxi-in times in both regions.
However, the variation across airports suggests that local specifics (traffic levels, used combinations of runway system / parking positions) contributed the varying taxi-in performance. It will be interesting to study the associated drivers in the future.
The levels of additional taxi-out times is generally higher for departing flights in comparison to arrivals.
The additional taxi-out times for the study airports showed a clear association with the traffic levels during and post COVID-19 in Brazil.
This behaviour is less prominent for the European airports and may be linked to the partail use of runway system, terminals, and parking positions.
In general surface movement operations see a higher variation in Brazil than in Europe. 
Although trends might be masked and impacted by the available data for this comparison for Brazil, the sequencing of arrival flights appeared to be independent of the traffic volume. The increase in additional times in 2021 appeared to be linked to a change in terms of en-route / terminal airspace interface. For the European context, the overall reduction in air traffic resulted in lower pressure on the sequencing of arrivals. On average, arriving traffic at all airports observed a lower additional times.
Flight time variability was obviously affected by the varying traffic levels. However, the Brazilian system is less impacted by seasonal variation than the European system.

Political priorities require to address the impact of air transportation on climate change. 
There is a growing interest in both regions to better quantify the potential benefit pool actionable by air navigation.
This report develped a first approach to better quantify inefficiencies observed in the taxi-in and taxi-out phase.
Higher operational performance will ultimately lead to higher levels of fuel efficiency and lower fuel burn. 
Absolute numbers in terms of fuel burn / CO~2~ emissions are linked to the volume of air traffic and aircraft types in service. 
The latter impacts a direct comparison and require more research for future editions.
This comparison shows the potential benefit pool at the different airports. This pool provides a higher margin of improvement at airports with higher levels of air traffic and large (heavy) aircraft. As such, the role of the airport within the system - heavy aircraft & international connectivity - is a fundamental aspect in terms of addressing the contribution of air navigation.


This second edition of the operational comparison between Brazil and Europe allowed to further harmonise the application of GANP performance measures and identified areas for further research and joint developments.
Both groups, Performance Section of DECEA and Performance Review Unit of EUROCONTROL, plan to continue the close collaboration and expand on the analyses of this report. 
This report will be updated throughout the coming years under the umbrella of the DECEA-EUROCONTROL memorandum of cooperation. 
Building on this collaboration, the idea is to establish a web-based rolling monitoring complementing this and future editions. A web-based monitoring will enable updates on a regular basis. 
Future editions will also enable to complement data time series and support the development of further use-case analyses. 
The lessons learnt of this joint project will also be coordinated with the multi-national PBWG and ICAO GANP Study sub-group concerned with the further development of the GANP KPIs.
