project:
  type: book
  output-dir: docs

execute:
  echo: false
  warning: false

book:
  title: "Brazil/Europe Comparison of Operational ANS Performance"
  author: |
    | DECEA Performance Section
    | EUROCONTROL Performance Review Unit
  date: "28. October 2022"
  chapters:
    - index.qmd
    - 00-front-matters.qmd
    - 00-executive.qmd
    - 01-intro.qmd
    - 02-system-overview.qmd
    - 03-traffic-characterisation.qmd
    - 04-predictability.qmd
    - 05-capacity.qmd
    - 06-efficiency.qmd
    - 07-environment.qmd
    - 08-conclusions.qmd
  appendices:
    - 90-back-matters.qmd
    - references.qmd
  output-file: "BRA-EUR-2022"

bibliography: [references.bib, book.bib, packages.bib, bra-eur.bib]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    papersize: a4
    # pandoc_args:
    # - "--lua-filter=columns-to-table.lua"
    # - "--luafilter lua-column-div.lua"
    # # control 2-column layout in pdf output
    # # https://stackoverflow.com/questions/73166794/put-2-chunks-of-code-side-by-side-in-rmarkdown-or-quarto

    fig-pos: 'h'
    geometry:
    - top=30mm
    - right=30mm
    - left=30mm
    - bottom=30mm
    - heightrounded
    include-in-header:
      text: |
        \usepackage{pdfpages}
        \pagenumbering{gobble}

  docx:
    toc: true
    number-sections: true
    highlight-style: github
# header-includes:
#     - \usepackage{pdfpages}




filters:
  - columns.lua

editor: visual
